---
name: check pr

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * 5"  # Every friday at 3 AM

jobs:
  check_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Set git config
        run: |
          git config diff.renameLimit 99999
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.5.1
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            python check_file.py $file
          done
